services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    restart: unless-stopped
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    restart: unless-stopped
  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411'
