spring:
  docker:
    compose:
      lifecycle-management: start_only
      enabled: false
  datasource:
    url: jdbc:postgresql://113.172.227.79:5432/postgres
    username: postgres
    password: Root@123
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
  freemarker:
    suffix: .ftl
  thymeleaf:
    check-template: false
    cache: false
    template-resolver-order: 1
  mvc:
    log-request-details: true
    dispatch-trace-request: true
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 5m
  data:
    web:
      pageable:
        default-page-size: 2
    redis:
      host: 113.172.227.79
      port: 6379
      database: 1
logging:
  level:
    root: INFO
    web: TRACE
    dev.hobie.thymeleaf: TRACE
