spring:
  devtools:
    add-properties: false
  jpa:
    open-in-view: true
    show-sql: true
  mvc:
    log-request-details: true
    dispatch-trace-request: true
logging:
  level:
    root: info
    web: info
    com.example.modulith: info